# Generated by Django 3.2.7 on 2021-10-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('due_date', 'status')},
        ),
    ]
