# Generated by Django 3.2.7 on 2021-09-12 22:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20210908_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.AddField(
            model_name='invoice',
            name='market',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='invoice.market'),
            preserve_default=False,
        ),
    ]
