# Generated by Django 3.2.7 on 2021-09-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20210912_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='message',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.market'),
        ),
    ]
